apiVersion: argoproj.io/v1alpha1

kind: ApplicationSet

metadata:
  name: p3-app
  namespace: argocd

spec:
  generators:
    - list:
        elements:
          - version: v1
          - version: v2

  template:
    metadata:
      name: '{{version}}'

    spec:
      project: p3-project

      source:
        repoURL: https://github.com/Frillas/aroullea_app
        path: 'app/overlays/{{version}}'
        targetRevision: main

      destination:
        server: https://kubernetes.default.svc
        namespace: 'dev'

      syncPolicy:
        automated:
          selfHeal: true
          prune: true
