global:
  edition: ce

  hosts:
    domain: gitlab.local
    externalIP: 127.0.0.1

  redis:
    host: redis-master.gitlab.svc.cluster.local

  psql:
    host: postgres-postgresql.gitlab.svc.cluster.local
    password:
      secret: postgres-postgresql
      key: postgres-password

  appConfig:
    artifacts:
      enabled: false

    lfs:
      enabled: false

    uploads:
      enabled: false

    packages:
      enabled: false

    backups:
      bucket: gitlab-backups
      tmpBucket: gitlab-tmp

minio:
  enabled: true

  image:
    registry: docker.io
    repository: minio/minio
    tag: latest

  auth:
    rootUser: minio
    rootPassword: minio123

  defaultBuckets: gitlab-backups

registry:
  enabled: false

gitlab:
  toolbox:
    backups:
      objectStorage:
        backend: s3
        config:
          secret: gitlab-minio-secret
          key: config

certmanager-issuer:
  email: aroullea@student.42angouleme.fr
