Vagrant.configure("2") do |config|
 	config.vm.box = "generic/debian12"
 	config.vm.box_version = "4.3.12"
#config.vm.synced_folder ".", "/vagrant", type: "9p"

   config.vm.define "aroulleaS" do |master|
		master.vm.hostname = "aroulleaS"
		master.vm.network "private_network", ip: "192.168.56.110"
		master.vm.provider "libvirt" do |libvirt|
			#libvirt.host = "aroulleaS"
			libvirt.cpus = 1
			libvirt.memory = "1024"
			libvirt.driver = "qemu"
		end
	   master.vm.provision "shell", path: "./scripts/master.sh"
	end

	config.vm.define "aroulleaSW" do |worker|
		worker.vm.hostname = "aroulleaSW"
		worker.vm.network "private_network", ip: "192.168.56.111"
		worker.vm.provider "libvirt" do |libvirt|
			#libvirt.host = "aroulleaSW"
			libvirt.cpus = 1
			libvirt.memory = "1024"
			libvirt.driver = "qemu"
		end
	   worker.vm.provision "shell", path: "./scripts/worker.sh"
	end
end
