# first machine hostname followed by S (like server)
# second machine hostname followed by SW (like ServerWorker)

# first machine IP -> 192.168.56.110
# seconde machine IP -> 192.168.56.111

# connect with SSH without password

# install K3s on both machines:
#   -> (Server) installed in controller mode
#   -> (ServerWorker) installed in agent mode

SERVICES = {
  'Server' => {
    ip: '192.168.56.110',
    ports: { 8080 => 8080 }
  },
  'ServerWorker' => {
    ip: '192.168.56.111',
    ports: { 8081 => 8081 }
  }
}

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "512"
    vb.cpus = 1
    vb.name = "Server"
  end

  config.vm.define "tdausqueS" do |controller|
    controller.vm.hostname = "tdausqueS"
    controller.vm.network "private_network", ip: "192.168.56.110"
    #controller.vm.network "forwarded_port", guest: 8080, host: 8080
   
    config.vm.provision "shell", name: "script", path: "script.sh", args: ["192.168.56.110"] 
  end
end
